spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jflashcards
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/jflashcards
    user: postgres
    password: root
