INSERT INTO flashcards
    (question, asnwer)
VALUES ('Hibernate',
        'Framework będący jednym z najpopularniejszych implementacji persistence API(JPA).
Odpowiada za wygodną komunikację aplikacji z bazą danych. Umożliwia wykonanie ORM – mapowania obiektowo-relacyjnego, czyli odzwzorowanie obiektów klas na bazę danych.'),
       ('final',
        'Słowo kluczowe, które zależnie od użytego kontekstu oznacza niezmienność deklarowanego elementu(klasy-nie może być dziedziczona, pola-nie może zmienić swojej wartości, metody-nie może zostać nadpisana.'),
       ('finally',
        'Finally oznaczamy blok kodu, któy zawsze ma się go wykonać. Używa się przy obsłudze wyjątków(po bloku catch lub bezpośrednio po try). Przydatny do czyszczenia zasobów, zamykania streamów i połączeń do bazy danych.'),
       ('finalize',
        'Metoda z klasy Object, przestarzała. Jest wykonywana tylko jeden raz zaraz przed tym jak GC chce usunąć obiekt z pamięci. Możemy sami ją wywołać-poleganie na niej to zła praktyka!'),
       ('Test Driven Development (TDD)',
        'Technika tworzenia oprogramowania polegająca na tym, że pierw tworzy się testy do nieistniejącej funkcjonalności a dopiero potem pisze się kod implementujący ją.'),
       ('Wzorce projektowe',
        'Zbiór najlepszych praktyk z gotowymi rozwiązaniami dla wybranych problemów napotykanych w trakcie projektowania rozwiązań zorientowanych obiektowo. Rozróżniamy wzorce: behawioralne, strukturalne oraz kreacyjne'),
       ('Wzorce kreacyjne',
        'Dotyczą Dotyczą sposób tworzenia klas, metod, oraz typów danych. Rozróżniamy : Abstract factory, Builder, Singleton'),
       ('Wzorce behawioralne',
        'Dotyczą zachowania współpracujących obiektów. Rozróżniamy : Strategy, Visitor, Observer'),
       ('Wzorce strukturalne',
        'Dotyczą zależności powiązanych ze sobą obiektów. Rozróżniamy : Decorator, Facade, Composite'),
       ('GIT',
        'Git jest to rozproszony system kontroli wersji. Śledzi zmiany w kodzie, zapisuje jego wersje, pozwala pracować wielu programistom na jednym projekcie. GitHub i GitLab to hostingowe serwisy internetowe wykorzystujące system Git.'),
       ('equals()',
        'Metoda zdefiniowana w klasie Object i służy do porównywania typów obiektowych. Domyślna implementacja metody equals() sprowadza się jednak jedynie do porównania referencji ==, czyli w większości przypadków nie jest zbyt użyteczna. W klasach, których obiekty będziemy ze sobą porównywali powinniśmy ją nadpisać.'),
       ('==',
        'Wykorzystywana przede wszystkim do porównywania typów prostych. W przypadku typów obiektowych porównuje referencje, a nie wartość strukturalną obiektów'),
       ('JVM',
        'Java Virtual Machine. Jest to maszyna wirtualna oraz środowisko zdolne do wykonywania kodu bajtowego. Głównym założeniem Javy jest slogan "napisz raz, uruchom gdziekolwiek". Aby osiągnąć ten cel potrzebna była właśnie wirtualna maszyna.'),
       ('Kompilacja',
        ' Kompilacja polega na przetłumaczeniu programu napisanego w Javie na kod wykonywalny, tzw. Bytecode. Kompilację wykonujemy przy użyciu specjalnego narzędzia tzw. kompilatora.'),
       ('JDK',
        'Oznacza dokładnie Java Development Kit. Uproszczając mówimy tutaj o zestawie narzędzi do developowania (tworzenia) aplikacji. Zawiera JRE, a co za tym idzie-JVM.'),
       ('JRE',
        'Java Runtime Environment, tj. Środowisko Uruchomieniowe Javy. JRE składa się z Wirtualnej Maszyny Javy (tzn. zawiera JVM) oraz zestawu klas i narzędzi niezbędnych dla uruchamiania programów napisanych w Javie.'),
       ('JDBC',
        'Java DataBase Conectivity - jest to interfejs pozwalający na ustanowienie połączenia do bazy danych z poziomu aplikacji napisanej w Javie.'),

